travis:
  secure:
    BINSTAR_TOKEN: gFWhjlDlIqxIE4J75ouEYxmSegCawCENeXsweX1UGPLEhqCWjR2drGZ5KsNPnBBXF9dUczggO0IIyFPnjK9gVKSQp5vNpsZ8cGiRnUqXm2ZyNc9RUwuVb91SfUbD+Qv9gFnuGGn2ksml6UvvJbAPhxHyK68taV7KoUBz6+FIGSFowM6rhi3O9+xZj6+4snjoVbD6AMYQ0GWNzX74r46H4A/DqkmxbmWWcJ9QFyX1t3tWAd9YRNrDqsTqiWTETeF6+a1DTKx/OOYLWNjEBzzGtzEospoqp3uV23MMiMNu7z6bHXKIWPs4gipnBrQF3Hyih5gATCv05cQewpSDOzM0AShiWCQoNo8riT+mxiw/9W6fwOiGngtZYJSGR3CFmDM20890OQpXRXqDnr4e4kiW6A1AFycbwTUtHgBbYdX/0KBJJwTdLRJcRYd3hvpc2Wk4paPs58RxMTk5xjhvnEzM6QbR1G4rK1fsk2VIzIA/JNoYVNfJAlLTYyESJuDp6dNL16RflZXECNckydVaH7VZrPenGWPBcyHDZOeevydohw1LOfzvA3sy2sL1VpjxiLYTqYIMr3MB0YSIp0qCET7htc4F51ryZEVM5XXhDM4x7P1DAOiBWsqs9r6hN+Vxq+YGTHMVHhnojoMNkukwqqDEj0ksC15kgZdFuV27C2+lQqE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
