travis:
  secure:
    BINSTAR_TOKEN: oFbYe5FiJPwJz0AZAgOkXBAa2nZ3aSk2QK3sG0nr83r6m2zNWCoNEyIFRqrnOVjYGbZ91Trq7p5JxQrviotW8jLKLO2jfKh3ceNNuViijCUdrVyIyzXIq4v/CswofpErMI6GBL6+wec10n9DX5yTvhkNqOectInYlGys1Rw1Px/PpmjAbsaXFAfiGDP7jX8WdHFhlsvYac1AxPPEAYwii6P1+iTZ4Y4GMXd5fmFbT1Rj5U+pe4uq9KR3cDKPs0OYVlQ1AD3dTRte4k+neIXZ/mmtaRXuZhO9zzm4va3QTp2Sp76TN5ii+NFFuMtDXixGJJeHVyPZQibYup5PI6wcWOY6ZLvhZAFkg9kqaPMyp6G8stXWws6/A0n4PxbbE7jon6A6p9uvVVZ63jiwJq75riRwR2/ETGKAOMMaJy4tiqc7E1TVrcbK1cirCdaditkIj2MEW6eiN3oxBfVNoGHzYf7QLBJ1p6SqJDzijg38Vk2iMD7VBbvTxMbqGAS9R4lDA/c0YneUBQWy1l4brSjDOrCvVZrzwb/4XuQmipV91hr3ry7lon/0bUwrpIL0ZE3MGyoUDqiF6Q2L0stl/ePoyMKu19O+vgcK1L2FIkTJ4elAoJ3mCrmHk07EA4ozidqsiH7IZzDA+RkRkoFZMXrpToSurF0PFBRVFSHOO4GA3O0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
