travis:
  secure:
    BINSTAR_TOKEN: ekHET5Eb7K0+6QxyYO1BOZMdHP8Ao3MmhAbHegvKFsQ+SBL5i3MQRyP+u21sACtC8lSq3w+w1/kx1nEPhbNpdSKtGmHUKOYLIDJp93ptlVLaa3Ndz3bT4YKZc+Uz5jwATcoi/gRQE1WilQG2ZQzze/xC9WD+s/BzCIV/5/I8lk8eVDikA+cm2PybCfIBnub8TUKTTI4dUFLlLj/R+QfZjo8RcSFNFwl5QHaRF03szV0VP7Pwc9RRnnwzFB+576tUl1ZOwInoZdGZT4zpBD9BTt0ERdBRwY8p7POT8UJzNgeSS8Cn/sJUZa175eqqhdIl9rT1fGsJziORM+iGJ+CE7U9FeF+g6ajEypdizjBHkiqtv8K/EZxBOCKj2zfANd8plbaCGHwnxnPdw/7bCe+6/YaYhFCCsOLmbHTJ9EiL28xAjFD+UBUlmJF1BhgG3iLM8oW0DaCLj454BYXKeZ6TA0SZ0dmSLjDQKy+05ZpVtrf/M9QBBz8J6hoCJ0RhI4yHVgkf6/NI5NWdoj8sCfh/FYQqLdxQsb+SVCVfvkfAoM3P/Bxr1qCkdoAYY0zhPygOcr4+nPxua7XO8AzWFeJokcme1Xz2bLT5eYRf8TWod1DNRVCBqJvqm2Pyz1/jSeZ1bBsfV5l2AnYkgpKOSFY5Tl7EHfI5iD3PlKGKRgj9Lg8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
